### ISSUE TITLE
Qulacs problems with CUDA 11.6

### ISSUE THREAD

**Issue by ovhpa** [qulacs/qulacs#312]
Hi,
I encountered 2 problems while installing Qulacs for GPU on a server running ubuntu server 22.04 with the following details:
gcc version:
```
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
nvcc version: 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```
CUDA: 11.6 Driver: 510.73.05

Compilation using: `python setup_gpu.py install` (but same problem appear with `./script/build_gcc_with_gpu.sh`)

### Problems

1. The first problem is at compile time.
The file `cuda_compile_1_generated_memory_ops.cu` receive the following error while compiling:
```
/usr/include/c++/11/type_traits:79:52: error: redefinition of ‘constexpr const _Tp std::integral_constant<_Tp, __v>::value’
   79 |   template<typename _Tp, _Tp __v>
      |                                                    ^                           
/usr/include/c++/11/type_traits:67:29: note: ‘constexpr const _Tp value’ previously declared here
   67 |       static constexpr _Tp                  value = __v;
      |                             ^~~~~
```
Similarly, the file `update_ops_control_multi_target_single.c` received the same error:
```
/usr/include/c++/11/type_traits:79:52: error: redefinition of ‘constexpr const _Tp std::integral_constant<_Tp, __v>::value’
   79 |   template<typename _Tp, _Tp __v>
      |                                                    ^                           
/usr/include/c++/11/type_traits:67:29: note: ‘constexpr const _Tp value’ previously declared here
   67 |       static constexpr _Tp                  value = __v;
      |                             ^~~~~
```

2. The second problem is at execution time.
After working out the first problem, Qulacs failed in setting `QuantumStateGpu` with the error:
```
Error: <...>/qulacs/src/gpusim/memory_ops.cu:71, code: 209, reason: no kernel image is available for execution on the device
```

### workaround
I am not sure if this will be helpful for anyone, but I manage a workaround for the 2 errors, by adding:
```
set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_XX,code=sm_XX --std c++17")
```
where XX is the compute-capability of the GPU (for example 53 for 5.3), and
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")
```
In the `CMakeLists.txt` and `src/CMakeLists.txt` files, respectively.
The `-gencode arch=compute_XX,code=sm_XX` part is necessary for nvcc to compile a kernel for a given architecture (problem 2) and the `-std=c++17` is necessary for the gcc/nvcc version (problem 1).

Now I have Qulacs nicely working on CUDA 11.6 ;)

Best,

**Comment by kotamanegi** [comment]
Hello :wave:
Unfortunately, CUDA 11.6 does not officially support `gcc-11` (GCC version 11) at this moment.
I think it is a duplicated issue so I would like to discuss the solution here: https://github.com/qulacs/qulacs/issues/322
