### ISSUE TITLE
Unable to import QuantumStateGpu from qulacs

### ISSUE THREAD

**Issue by jxc0229** [qulacs/qulacs#650]
Hi, I was able to install qulacs-gpu successfully on linux system and I'm working in a Python environment (Python 3.9.19). When I tried to import QuantumStateGpu using `from qulacs import QuantumStateGpu`, it gives the following error message:
```
from qulacs import QuantumStateGpu, QuantumCircuit, StateVector
ImportError: cannot import name 'QuantumStateGpu' from 'qulacs' (/home/ubuntu/miniconda3/envs/research/lib/python3.9/site-packages/qulacs/__init__.py)
```
I saw GPU was mentioned in the Python Advanced guide, but is it currently supported for Python API at all? Thanks in advance for any help!

**Comment by KowerKoint** [comment]
To get GPU support, you have to manually install qulacs by following commands.

```
git clone https://github.com/qulacs/qulacs.git
cd qulacs
USE_GPU=Yes pip install .
```
